from docx import Document

document = Document()

document.add_heading('Lab Assignment: Secure Authentication in Python', 0)

document.add_heading('Introduction', level=1)
document.add_paragraph('This lab is designed to provide you with hands-on experience in developing a secure authentication module in Python. You will learn how to implement essential security features, such as password hashing and salting, to protect user credentials. Additionally, you will practice writing unit tests to ensure the correctness and security of your code.')

document.add_heading('Objectives', level=1)
document.add_paragraph('By the end of this lab, you will be able to:')
document.add_paragraph('- Understand the importance of secure password storage.', style='List Bullet')
document.add_paragraph('- Implement password hashing and salting using Python\'s hashlib and os modules.', style='List Bullet')
document.add_paragraph('- Develop a set of unit tests to verify the functionality of your authentication module.', style='List Bullet')
document.add_paragraph('- Create a simple command-line interface for user registration and login.', style='List Bullet')

document.add_heading('Tasks', level=1)
document.add_paragraph('1.  Create a new Python file named `user.py` and define a `User` class with the following attributes:')
document.add_paragraph('- `username`: The user\'s username.', style='List Bullet 2')
document.add_paragraph('- `hpass`: The user\'s hashed password.', style='List Bullet 2')
document.add_paragraph('- `salt`: The salt used to hash the password.', style='List Bullet 2')
document.add_paragraph('2.  Create a new Python file named `auth.py` and implement the following functions:')
document.add_paragraph('- `get_salt(length)`: Generates a random salt of the specified length.', style='List Bullet 2')
document.add_paragraph('- `get_hash(input_string)`: Hashes the input string using the SHA-256 algorithm.', style='List Bullet 2')
document.add_paragraph('- `bytes_to_hex(byte_array)`: Converts a byte array to a hexadecimal string.', style='List Bullet 2')
document.add_paragraph('- `user_to_json(user)`: Converts a `User` object to a JSON string.', style='List Bullet 2')
document.add_paragraph('- `json_to_user(json_string)`: Converts a JSON string to a `User` object.', style='List Bullet 2')
document.add_paragraph('- `find_user(user_list, username)`: Finds a user in a list of users by their username.', style='List Bullet 2')
document.add_paragraph('- `save_users(user_list, filepath)`: Saves a list of users to a JSON file.', style='List Bullet 2')
document.add_paragraph('- `load_users(filepath)`: Loads a list of users from a JSON file.', style='List Bullet 2')
document.add_paragraph('3.  Create a new Python file named `user_registration.py` and implement the following function:')
document.add_paragraph('- `create_user(username, password)`: Creates a new `User` object with a hashed password and a random salt.', style='List Bullet 2')
document.add_paragraph('4.  Create a new Python file named `test_auth.py` and write unit tests for the following functions in `auth.py`:')
document.add_paragraph('- `get_salt()`', style='List Bullet 2')
document.add_paragraph('- `get_hash()`', style='List Bullet 2')
document.add_paragraph('- `json_to_user()`', style='List Bullet 2')
document.add_paragraph('- `user_to_json()`', style='List Bullet 2')
document.add_paragraph('- `find_user()`', style='List Bullet 2')
document.add_paragraph('- `save_load_users()`', style='List Bullet 2')
document.add_paragraph('5.  Create a new Python file named `main.py` and implement a command-line interface with the following options:')
document.add_paragraph('- `1-login`: Prompts the user for their username and password and verifies their credentials.', style='List Bullet 2')
document.add_paragraph('- `2-register`: Prompts the user for a new username and password and creates a new user account.', style='List Bullet 2')
document.add_paragraph('- `3-exit`: Exits the program.', style='List Bullet 2')

document.add_heading('Submission', level=1)
document.add_paragraph('Submit all the Python files you created (`user.py`, `auth.py`, `user_registration.py`, `test_auth.py`, and `main.py`) in a single zip file.')

document.add_heading('Grading', level=1)
document.add_paragraph('Your lab will be graded based on the following criteria:')
document.add_paragraph('- Correct implementation of the `User` class.', style='List Bullet')
document.add_paragraph('- Correct implementation of the functions in `auth.py`.', style='List Bullet')
document.add_paragraph('- Correct implementation of the `create_user()` function in `user_registration.py`.', style='List Bullet')
document.add_paragraph('- Completeness and correctness of the unit tests in `test_auth.py`.', style='List Bullet')
document.add_paragraph('- Correct implementation of the command-line interface in `main.py`.', style='List Bullet')
document.add_paragraph('- Code quality, including readability, comments, and adherence to Python best practices.', style='List Bullet')

document.save('Lab Assignment.docx')
